apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world-app
  type: LoadBalancer  # This will expose the app to the internet
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
